In [ ]:
import pandas as pd
# First way
pd.read_csv('Wheatherdata.csv')

          Day  Temperature  Windspeed climate
0  01-01-2017           32          6    Rain
1  01-02-2017           35          7   Sunny
2  01-03-2017           28          2    Snow
3  01-04-2017           24          7    Snow
4  01-05-2017           32          4    Rain
5  01-06-2017           32          2   Sunny

In [12]:
pd.read_excel("Wheather_data.xlsx")

         Day  Temperature  Climate
0 2026-01-01            35   Rainy
1 2026-01-02            32   Snow
2 2026-01-03            34   Snow
3 2026-01-04            35   Sunny
4 2026-01-05            31   Rainy
5 2026-01-06            30   Snow
6 2026-01-07            32   Sunny
7 2026-01-08            34   Sunny
8 2026-01-09            35   Snow
9 2026-01-10            31   Rainy

In [ ]:
# 3rd waay is using python dictonaries 
import pandas as pd

weather = {
    'day': ['1-1-2017', '1-2-2017', '1-3-2017'],
    'temperature': [32, 35, 34],
    'event': ['sunny', 'rainy', 'snow']
}

df = pd.DataFrame(weather)
df

        day  temperature  event
0  1-1-2017           32  sunny
1  1-2-2017           35  rainy
2  1-3-2017           34   snow

In [29]:
# 4th way is by creating python tuples

wheather = [
    ('1-1-2017', 32, 'Rain'),
    ('1-2-2017', 35, 'sunny'),
    ('1-3-2017', 36, 'snow')
]

df = pd.DataFrame(wheather, columns= ["day", "temperature", "event"])
df

        day  temperature  event
0  1-1-2017           32   Rain
1  1-2-2017           35  sunny
2  1-3-2017           36   snow

In [32]:
# another way using python dictonaries

wheather = [
    {'day':"1-1-2017",'temperature': 32,'event':"Rain"},
    {'day':"1-2-2017",'temperature': 35,'event':"sunny"},
    {'day':"1-1-2017",'temperature': 34,'event':"snow"}
]

df = pd.DataFrame(wheather)
df

        day  temperature  event
0  1-1-2017           32   Rain
1  1-2-2017           35  sunny
2  1-1-2017           34   snow