In [1]:
import pandas as pd

df = pd.read_csv("stock_data.csv",skiprows=2)
df
df = pd.read_csv("stock_data.csv", header = 1)
df

    WMT           4.61  484    65           n.a.
0  MSFT             -1   85    64     bill gates
1   RIL  not available   50  1023  mukesh ambani
2  TATA            5.6   -1  n.a.     ratan tata

In [2]:
# suppose if you are missing a header in you csv file use below method
df =pd.read_csv("stock_data.csv", header=None, names = ["tickers","eps","revenue","price","people"])
df
# tickers,eps,revenue,price,people

  tickers            eps  revenue price         people
0   GOOGL          27.82       87   845     larry page
1     WMT           4.61      484    65           n.a.
2    MSFT             -1       85    64     bill gates
3     RIL  not available       50  1023  mukesh ambani
4    TATA            5.6       -1  n.a.     ratan tata

In [ ]:
# supposeyour csv file is quite bigger and you just want print some of the rows then use below methods 
df = pd.read_csv("stock_data.csv", header=None,nrows=3)
df

       0      1    2    3           4
0  GOOGL  27.82   87  845  larry page
1    WMT   4.61  484   65        n.a.
2   MSFT  -1.00   85   64  bill gates

In [7]:
# if you csv file contains na values or not a number values  but you want to read them the use below metho 
df = pd.read_csv("stock_data.csv", na_values=("not available", "n.a."))
df

  GOOGL  27.82   87     845     larry page
0   WMT   4.61  484    65.0            NaN
1  MSFT  -1.00   85    64.0     bill gates
2   RIL    NaN   50  1023.0  mukesh ambani
3  TATA   5.60   -1     NaN     ratan tata

In [10]:
# in some cases you want a negative and in ome cases you dont want the negative at the same time the ;

df = pd.read_csv("stock_data.csv", na_values={
    'ep': ["not available", "n.a."],
    'revenue' : ["not available", "n.a.","-1"]
})
df

  GOOGL          27.82   87   845     larry page
0   WMT           4.61  484    65           n.a.
1  MSFT             -1   85    64     bill gates
2   RIL  not available   50  1023  mukesh ambani
3  TATA            5.6   -1  n.a.     ratan tata