In [1]:
import pandas as pd

df = pd.read_csv("stock_data.csv",skiprows=2)
df
df = pd.read_csv("stock_data.csv", header = 1)
df

    WMT           4.61  484    65           n.a.
0  MSFT             -1   85    64     bill gates
1   RIL  not available   50  1023  mukesh ambani
2  TATA            5.6   -1  n.a.     ratan tata

In [2]:
# suppose if you are missing a header in you csv file use below method
df =pd.read_csv("stock_data.csv", header=None, names = ["tickers","eps","revenue","price","people"])
df

# tickers,eps,revenue,price,people

  tickers            eps  revenue price         people
0   GOOGL          27.82       87   845     larry page
1     WMT           4.61      484    65           n.a.
2    MSFT             -1       85    64     bill gates
3     RIL  not available       50  1023  mukesh ambani
4    TATA            5.6       -1  n.a.     ratan tata

In [3]:
# supposeyour csv file is quite biugger and you just want print some of the rows then use below methods