In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('Wheatherdata.csv')
df

          Day  Temperature  Windspeed climate
0  01-01-2017           32          6    Rain
1  01-02-2017           35          7   Sunny
2  01-03-2017           28          2    Snow
3  01-04-2017           24          7    Snow
4  01-05-2017           32          4    Rain
5  01-06-2017           32          2   Sunny

In [ ]:
# df.shape

rows , columns = df.shape

# columns
rows

6

In [20]:
df.head(1)

df.tail(1)

          Day  Temperature  Windspeed climate
5  01-06-2017           32          2   Sunny

In [23]:
df.columns

Index(['Day', 'Temperature', 'Windspeed', 'climate'], dtype='str')

In [24]:
df[2:5]

          Day  Temperature  Windspeed climate
2  01-03-2017           28          2    Snow
3  01-04-2017           24          7    Snow
4  01-05-2017           32          4    Rain

In [ ]:
df.Temperature  # df.['Temperature]

0    32
1    35
2    28
3    24
4    32
5    32
Name: Temperature, dtype: int64

In [30]:
df[['Day', 'Temperature']]

          Day  Temperature
0  01-01-2017           32
1  01-02-2017           35
2  01-03-2017           28
3  01-04-2017           24
4  01-05-2017           32
5  01-06-2017           32

In [ ]:
# type(df['Temperature'])

pandas.Series

In [9]:
df['Temperature'].mean()

float(df['Temperature'].mean())

30.5